name: waydchatapp
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.0.20
  http: ^0.13.4
  google_sign_in: ^5.3.3
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase: ^9.0.3
  firebase_core: ^1.17.1
  firebase_database: ^9.0.16
  provider: ^6.0.3
  page_transition: ^2.0.5
  cloud_functions: ^3.2.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/placeholders/
  uses-material-design: true
